//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringSupporter.Resources.Localize {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EngineeringSupporter.Resources.Localize.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string todo_table_header_taskname {
            get {
                return ResourceManager.GetString("todo_table_header_taskname", resourceCulture);
            }
        }
        
        internal static string todo_table_header_planstart {
            get {
                return ResourceManager.GetString("todo_table_header_planstart", resourceCulture);
            }
        }
        
        internal static string todo_table_header_planend {
            get {
                return ResourceManager.GetString("todo_table_header_planend", resourceCulture);
            }
        }

        internal static string todo_table_header_predictionend {
            get {
                return ResourceManager.GetString("todo_table_header_predictionend", resourceCulture);
            }
        }
        
        internal static string todo_table_header_actualstart {
            get {
                return ResourceManager.GetString("todo_table_header_actualstart", resourceCulture);
            }
        }
        
        internal static string todo_table_header_actualend {
            get {
                return ResourceManager.GetString("todo_table_header_actualend", resourceCulture);
            }
        }
        
        internal static string todo_table_header_progress {
            get {
                return ResourceManager.GetString("todo_table_header_progress", resourceCulture);
            }
        }
        
        internal static string todo_table_header_progressforecast {
            get {
                return ResourceManager.GetString("todo_table_header_progressforecast", resourceCulture);
            }
        }
        
        internal static string todo_table_header_todayplanprogress {
            get {
                return ResourceManager.GetString("todo_table_header_todayplanprogress", resourceCulture);
            }
        }
        
        internal static string todo_table_header_delete {
            get {
                return ResourceManager.GetString("todo_table_header_delete", resourceCulture);
            }
        }
        
        internal static string todo_table_action_delete {
            get {
                return ResourceManager.GetString("todo_table_action_delete", resourceCulture);
            }
        }
        
        internal static string todo_header_title {
            get {
                return ResourceManager.GetString("todo_header_title", resourceCulture);
            }
        }
        
        internal static string todo_header_subtitle {
            get {
                return ResourceManager.GetString("todo_header_subtitle", resourceCulture);
            }
        }
        
        internal static string todo_addtask_title {
            get {
                return ResourceManager.GetString("todo_addtask_title", resourceCulture);
            }
        }
    }
}
